apiVersion:  apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
  namespace: my-web-app

spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: my-web-ctr
        image: 9145503154/my-app:latest
        ports:
        - containerPort: 8000

